# coding: utf-8
from catalog.models import Product, Category
category1 = Category.objects.create(name ='Бытовая техника', description='Надежная техника для дома и кухни.')
category2 = Category.objects.create(name ='Косметика и парфюмерия', description='Красота и ухоженность.')
category3 = Category.objects.create(name ='Спортивные товары', description='Всё для активного образа жизни.')
product1 = Product.objects.create(name ='Робот-пылесос ILIFE A7', description= 'Высокопроизводительный робот-пылесос с интеллектуальной системой навигации и возможностью влажной уборки', image='media/images/Робот-пылесос.jpeg', category= category1, price='24990', created_at='2024-01-01', updated_at='2024-01-02')
product2 = Product.objects.create(name ='Стиральная машина LG FH4G1JCS2', description= 'Энергоэффективная стиральная машина с технологией TrueSteam и функцией SmartThinQ', image='media/images/Стиральная машина.jpeg', category= category1, price='39990', created_at='2024-01-01', updated_at='2024-01-03')
product3 = Product.objects.create(name ='Парфюмированная вода Dior Jadore', description= 'Роскошный цветочный аромат с нотами жасмина, розы и персика', image='media/images/Духи.jpeg', category= category2, price='5990', created_at='2024-01-01', updated_at='2024-01-04')
product4 = Product.objects.create(name ='Крем для лица Clinique Moisturizing Lotion+', description= 'Увлажняющий крем для всех типов кожи, обогащенный питательными веществами', image='media/images/Крем для лица.jpeg', category= category2, price='2590', created_at='2024-01-01', updated_at='2024-01-05')
product5 = Product.objects.create(name ='Набор для макияжа NYX Professional Makeup', description= 'Палетка теней для век с широкой цветовой гаммой и высокой пигментацией', image='media/images/Набор для макияжа.jpeg', category= category2, price='1990', created_at='2024-01-01', updated_at='2024-01-06')
product6 = Product.objects.create(name ='Беговая дорожка Horizon Fitness T101', description= 'Надежная домашняя беговая дорожка с богатым функционалом и плавным ходом', image='media/images/Беговая дорожка.png ', category=category3, price='49990', created_at='2024-01-01', updated_at='2024-01-07')
product7 = Product.objects.create(name ='Велотренажер Bowflex VeloCore', description= 'Инновационный велотренажер с возможностью наклона и поворота рамы для более интенсивной тренировки', image='media/images/Велотренажер.jpeg', category= category3, price='89990', created_at='2024-01-01', updated_at='2024-01-08')
product8 = Product.objects.create(name ='Гантели Bowflex SelectTech 552', description= 'Регулируемые гантели с диапазоном от 2,3 до 24 кг, заменяющие 15 пар обычных гантелей', image='media/images/Гантели.jpeg', category= category3, price='14990', created_at='2024-01-01', updated_at='2024-01-09')
product9 = Product.objects.create(name ='Телевизор Samsung QE55Q60A', description= 'Высококачественный QLED-телевизор с технологией 4K HDR и функцией Smart TV', image='media/images/Телевизор.jpeg', category=category1, price='64990', created_at='2024-01-01', updated_at='2024-01-10')
