# Generated by Django 5.1.3 on 2024-12-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(blank=True, max_length=500, verbose_name='Содержимое'),
        ),
    ]
